### ISSUE TITLE
Export won't maintain all consumer fields

### ISSUE THREAD

**Issue by csabatini** [romanovskyj/gongfig#42]
Specifically with consumers, I found that ```export``` persists the id and username. But there can be basic auth and key auth associated with the consumer. So if I ```export```, ```flush```, and ```import```, consumers can be in a different state. Would it make sense to have an option to exclude a resource type or id?

A question for you as the author: how do you intend the flow of updating the Kong config to work? Since ```import``` doesn't PATCH pre-existing resources, I was thinking you would ```flush``` and then run ```import``` again? 

In my Kong instance that uses the key-auth plugin, running ```flush``` can delete the consumer that's required to delete the rest of the resources, so I need to preserve it.

**Comment by csabatini** [comment]
This would be fine with me, but is it possible? I noticed that a GET request to the consumer endpoint returns these fields, but not the key field: created_at, id, username, type. I'm guessing this is for security reasons

**Comment by romanovskyj** [comment]
As for `key-auth` there should be additional GET request as you said, I will do the PR in the near future.

As for `basic-auth`, it looks like it is not possible to reupload the specified password :(, I have created the corresponding issue for it: https://github.com/Kong/kong/issues/4237

Let me know if you see any other solutions for this problem.

**Comment by csabatini** [comment]
Thanks for the update and for also testing the basic auth. Look forward to seeing your PR for key auth

**Comment by romanovskyj** [comment]
#44 @csabatini I have created PR for that, please check if it is what you expected.

**Comment by romanovskyj** [comment]
PR is merged, so closing the issue, let me know if you see any problems here.
