### ISSUE TITLE
Plugin export/import feature

### ISSUE THREAD

**Issue by alex-vasilchenko-md** [romanovskyj/gongfig#46]
Hi @romanovskyj ! The tool is really nice and it worked for my simple Kong 1.0.3 setup with services and routes!

I had a quick look into the code and found out that there is PluginsPath and looks like export/import for plugins is planned but I didn't see it was used in https://github.com/romanovskyj/gongfig/blob/master/pkg/actions/export.go
Are you planning to add plugin export/import feature?

**Comment by romanovskyj** [comment]
Hi, all collections are fully supported and plugins also. https://github.com/romanovskyj/gongfig/blob/master/pkg/actions/export.go#L164 it is obtained here. Anyway, if your plugin is not exported correctlt, let me know.

**Comment by alex-vasilchenko-md** [comment]
Git it! thank you very much!
