### ISSUE TITLE
Not exporting config correctly

### ISSUE THREAD

**Issue by Ilshidur** [romanovskyj/gongfig#48]
Hello.

It seems like the export tool does not export the Kong configuration correctly.

Example of an exported config here : https://gist.github.com/Ilshidur/4766e3c263627e6767a910d74ea92151

**The issue :**

When having an upstream that has **1** target, the exported upstream has multiple targets, and those are the targets of other upstreams.

Anyway, thanks for this amazing tool :smile:

**Comment by romanovskyj** [comment]
Thank you for the reporting, I fixed the issue when upstream has targets of other upstreams. 

As for the one target vs multiple targets, it does not look clear: as far as I see, you have four different targets and all they have suitable names. Are you sure you should have only one target? Do you have one target by api `<kong-url>/upstreams/<upstream_id>/targets` ?

#49

**Comment by romanovskyj** [comment]
As for now, I am closing it, let me know if you still have this problem.

**Comment by Ilshidur** [comment]
This is great ! Sorry for the late answer, I could only try this fix at work.

Thank you very much !
